name: Windows CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.11.1'
          arch: 'win64_msvc2022_64'

      - name: Configure CMake
        run: >
          cmake
          -B build
          -S .
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}/.."

      - name: Build
        run: cmake --build build